import ann.ann_dataprep as dp
import os

print ("\033[93mCreating META files\033[39m")
dir = "ann/thyroid-disease/"
dp.createMETAclasses(dir)
dp.createMETAvalues(dir)
print ("\033[93mCreating merged dataset file\033[39m")
dp.createDataset(dir)
print ("\033[93mFinding empty columns\033[39m")
empty = dp.findEmptyColumns('data.dat')
print ("\033[93mMocking unknown values\033[39m")
dp.mockValues('data.dat', 'output.dat')
os.remove('data.dat')
os.rename("output.dat",'data.dat')
print ("\033[93mEnumerating categorical data\033[39m")
dp.textToNum('data.dat')
os.remove('data.dat')
os.rename("output.csv",'data.dat')
print ("\033[93mRemoving Threash Data\033[39m")
useless = dp.findkeywordColumns('data.dat',"measured")
dp.removeRangeColumns('data.dat',empty)
dp.removeRangeColumns('data.dat',useless)
print ("\033[93mRemoving multiple class records\033[39m")
dp.oneClassOnly('data.dat', 'data.csv')
